import Navbar from './Navbar';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { getUrlLastIndex, capitalizeFirstLetter } from '@/helpers/string';
const Layout = ({children}: {children: React.ReactNode}) => {
    const {pathname} = useRouter();

    let modiPathName = getUrlLastIndex(pathname);
    let title = modiPathName ? 'Airbnb - ' + capitalizeFirstLetter(modiPathName) : 'Airbnb';

    return ( 
        <div className="py-4 px-8 flex flex-col min-h-screen max-w-7xl mx-auto">
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/airbnb-fav.png" />
            <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/datepicker.min.js" async></script>
        </Head>
            <Navbar />
            { children }
        </div>
    );
}
 
export default Layout;